require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/short_urls", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ShortUrl. As you add validations to ShortUrl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ShortUrl.create! valid_attributes
      get short_urls_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      short_url = ShortUrl.create! valid_attributes
      get short_url_url(short_url)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_short_url_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      short_url = ShortUrl.create! valid_attributes
      get edit_short_url_url(short_url)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ShortUrl" do
        expect {
          post short_urls_url, params: { short_url: valid_attributes }
        }.to change(ShortUrl, :count).by(1)
      end

      it "redirects to the created short_url" do
        post short_urls_url, params: { short_url: valid_attributes }
        expect(response).to redirect_to(short_url_url(ShortUrl.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ShortUrl" do
        expect {
          post short_urls_url, params: { short_url: invalid_attributes }
        }.to change(ShortUrl, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post short_urls_url, params: { short_url: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested short_url" do
        short_url = ShortUrl.create! valid_attributes
        patch short_url_url(short_url), params: { short_url: new_attributes }
        short_url.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the short_url" do
        short_url = ShortUrl.create! valid_attributes
        patch short_url_url(short_url), params: { short_url: new_attributes }
        short_url.reload
        expect(response).to redirect_to(short_url_url(short_url))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        short_url = ShortUrl.create! valid_attributes
        patch short_url_url(short_url), params: { short_url: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested short_url" do
      short_url = ShortUrl.create! valid_attributes
      expect {
        delete short_url_url(short_url)
      }.to change(ShortUrl, :count).by(-1)
    end

    it "redirects to the short_urls list" do
      short_url = ShortUrl.create! valid_attributes
      delete short_url_url(short_url)
      expect(response).to redirect_to(short_urls_url)
    end
  end
end
